import 'package:flutter_test/flutter_test.dart';
import 'package:escpos/escpos.dart' show CapabilityProfile, Ticket;
import 'package:fifty_printing_engine/src/core/print_ticket.dart';
import 'package:fifty_printing_engine/src/models/paper_size.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late CapabilityProfile profile;

  setUpAll(() async {
    profile = await CapabilityProfile.load();
  });

  group('PrintTicket', () {
    test('stores paperSize from constructor', () {
      final ticket80 = PrintTicket(PaperSize.mm80, profile);
      expect(ticket80.paperSize, PaperSize.mm80);

      final ticket58 = PrintTicket(PaperSize.mm58, profile);
      expect(ticket58.paperSize, PaperSize.mm58);
    });

    test('extends escpos Ticket', () {
      final ticket = PrintTicket(PaperSize.mm80, profile);
      expect(ticket, isA<Ticket>());
    });

    test('can add text content', () {
      final ticket = PrintTicket(PaperSize.mm80, profile);
      ticket.text('Hello World');
      // bytes are generated by escpos Ticket
      expect(ticket.bytes, isNotEmpty);
    });

    test('can add feed and cut commands', () {
      final ticket = PrintTicket(PaperSize.mm80, profile);
      ticket.text('Test');
      ticket.feed(2);
      ticket.cut();
      expect(ticket.bytes, isNotEmpty);
    });

    test('mm58 and mm80 produce different internal paper size', () {
      final ticket58 = PrintTicket(PaperSize.mm58, profile);
      final ticket80 = PrintTicket(PaperSize.mm80, profile);

      // Both are valid tickets but with different paper sizes
      expect(ticket58.paperSize, isNot(equals(ticket80.paperSize)));
    });

    test('bytes starts empty before adding content', () {
      final ticket = PrintTicket(PaperSize.mm80, profile);
      // escpos Ticket initializes with some header bytes
      // The key thing is it is a valid byte list
      expect(ticket.bytes, isA<List<int>>());
    });
  });
}
