include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_pub_dependencies
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
